### ISSUE TITLE
Cucumber Mod Refrabricated(Fork)

### ISSUE THREAD

**Issue by MEMERSBELIKE** [KirboSoftware-Mods/mystical-refabricated-issue-page#1]
Hi, here is what happens when I try to start my game with Cucumber Refrabricated Fork and it's respected dependencies:

Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'porting_lib_tool_actions'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:loot_condition_type / porting_lib:can_tool_perform_action] at different raw IDs (19, 20)! If you're trying to override an item, use .set(), not .register()!
	at net.minecraft.class_2370.handler$zpl000$fabric-registry-sync-v0$setPre(class_2370.java:705)
	at net.minecraft.class_2370.method_46744(class_2370.java)
	at net.minecraft.class_2370.method_10272(class_2370.java:186)
	at net.minecraft.class_2378.method_39197(class_2378.java:118)
	at net.minecraft.class_2378.method_10230(class_2378.java:114)
	at io.github.fabricators_of_create.porting_lib.tool.loot.CanToolPerformAction.init(CanToolPerformAction.java:66)
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198)
	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy32.onInitialize(Unknown Source)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more

If you would like to see the full version:
[crash-2024-05-19_08.53.59-client.txt](https://github.com/KirboSoftware-Mods/mystical-refabricated-issue-page/files/15367201/crash-2024-05-19_08.53.59-client.txt)

Also for more background context I am running this on a MacBook Pro, and am relatively new to Minecraft modding, so I don't really know how to dive into the code and fix it.

**Comment by CassieRoseZA** [comment]
your using the wrong mystical agriculture you seem to be using mysticalagriculture: Mystical Agriculture: Refabricated 3.0.2
But the current version is 3.1.0

**Comment by CassieRoseZA** [comment]
https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture-refabricated-forked
